[CV-423][Web] Annual Financial Report Generation
XavierGuertin/CondoVision pull request #85
Opened 2024-04-14 21:04 UTC by Kadestery

**Click up Issue:** https://app.clickup.com/t/86azdbnvm

### Description:
PR implements the 'Finance' page. Integrates the PropertyFinanceCard into the FinanceComponent. Allows for Condo Management Companies to view financial reports of their properties.

#### User flow:
-CMC clicks on 'Finance' in navbar/dashboard
-CMC clicks on a property, finances of property is displayed

### Demo:
![AnnualFinancialReport](https://github.com/XavierGuertin/CondoVision/assets/97750132/30bee7bf-6bb9-4a78-bdb5-a4ef66de27fb)
![Pr test 2](https://github.com/XavierGuertin/CondoVision/assets/97750132/6698ddf5-fef0-472a-a8d8-a0270a618ade)
![Pr test 3](https://github.com/XavierGuertin/CondoVision/assets/97750132/e2f7cb11-605c-4b5e-93f3-9a4430860090)

2024-04-14 22:03 UTC, Kadestery commented
End-to-End tests passed prior to the refactoring push, working on more refactoring tomorrow once firebase limit resets

2024-04-19 19:48 UTC, Fetyali7 approved these changes
It would be great if you added more comments explaining things but other than that, it looks good to me, nicely done Kade!

2024-04-21 13:29 UTC, XavierGuertin approved these changes

2024-04-21 13:39 UTC, XavierGuertin requested changes
add some comments at the top of the class explaining what it does

2024-04-21 20:37 UTC, Kadestery commented on apps/native/screens/PropertyManagementScreen.tsx
sa

2024-04-21 20:37 UTC, Kadestery reviewed
Added comments in new push

2024-04-21 21:12 UTC, Fetyali7 approved these changes
Looks better now Kade!

2024-04-22 00:40 UTC, XavierGuertin approved these changes

2024-04-22 14:25 UTC, Adissuu approved these changes
Good job, good following of the code convention

2024-04-22 14:26 UTC, merged